import type { Metadata } from "next";
import { Toaster } from '@/components/ui/sonner';
import { Inter } from 'next/font/google'
import { NuqsAdapter } from "nuqs/adapters/next/app";
import '@liveblocks/react-ui/styles.css';
import '@liveblocks/react-tiptap/styles.css'
import "./globals.css";
import { ConvexClientProvider } from "@/provider/convex-client-provider/convex-client-provider";


const inter = Inter({
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} antialiased`}
			>
				<NuqsAdapter>
					<ConvexClientProvider>
						<Toaster />
						{children}
					</ConvexClientProvider>

				</NuqsAdapter>
			</body>
		</html>
	);
}
